name: PvPKit
version: 0.1.0
author: Aripot007
website: https://github.com/aripot007
api-version: 1.14
main: main.fr.aripot007.pvpkit.PvPKit

commands:
  pvpkit:
    description: Commande prncipale du pvpkit.
    aliases: pk, pvpk, pkit

permissions: []