name: PvPKit
version: 0.1.0
author: Aripot007
website: https://github.com/aripot007
api-version: 1.14
main: main.fr.aripot007.pvpkit.PvPKit

commands:
  pvpkit:
    description: Commande principale du pvpkit.
    aliases: pk, pvpk, pkit
    
  pvpkitadmin:
    description: Commande d'administration du PvPKit
    permission: pvpkit.admin
    aliases: pka, pkadmin, pvpkita, apk, adminpk

permissions:
  pvpkit.admin:
    default: op
    description: Permet l'utilisation des commandes d'administration